# Generated by Django 5.0.6 on 2024-06-06 08:51

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=100, verbose_name='Навык')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя мастера')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='Информация')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_driver', models.CharField(choices=[('лгк', 'Легковой'), ('грз', 'Грузовой'), ('пшх', 'Пешеход')], default='лгк', max_length=10, verbose_name='Водитель (д/н)')),
                ('cat', models.ManyToManyField(blank=True, related_name='masters', to='masters.category', verbose_name='Навык')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастеры',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='masters_mas_time_cr_4488cc_idx')],
            },
        ),
    ]
