# Generated by Django 5.0.6 on 2024-06-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
