# Generated by Django 5.0.6 on 2024-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_delete_uploadfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(db_index=True, max_length=50, verbose_name='Название объекта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотоотчет')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content', models.CharField(blank=True, max_length=250, verbose_name='Дополнительная информация')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объектов',
                'ordering': ['-date_create'],
                'indexes': [models.Index(fields=['-date_create'], name='masters_pho_date_cr_89ed89_idx')],
            },
        ),
    ]
