# Generated by Django 5.0.6 on 2024-06-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
