# Generated by Django 5.0.6 on 2024-06-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_delete_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Адрес (название) объекта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content', models.CharField(blank=True, max_length=250, verbose_name='Дополнительная информация')),
                ('is_onsite', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотоотчет')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('contract', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='masters.contract', verbose_name='Адрес объекта')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объекта',
            },
        ),
    ]
