# Generated by Django 5.0.6 on 2024-06-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_contract_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='contract',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='masters.contract', verbose_name='Адрес объекта'),
        ),
    ]
