# Generated by Django 5.0.6 on 2024-06-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_master_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='contract',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masters.contract', verbose_name='Адрес объекта'),
        ),
    ]
