# Generated by Django 5.0.6 on 2024-06-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_photos_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='master',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
