# Generated by Django 5.0.6 on 2024-07-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_remove_master_cat_remove_master_tags_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['date_create'], 'verbose_name': 'Объекты', 'verbose_name_plural': 'Объект'},
        ),
    ]
