# Generated by Django 5.0.6 on 2024-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='slug'),
        ),
    ]
