# Generated by Django 5.0.6 on 2024-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='О мастере'),
        ),
    ]
