# Generated by Django 5.0.6 on 2024-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='О мастере'),
        ),
    ]
