# Generated by Django 5.0.6 on 2024-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tagpost_remove_user_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagPost',
            new_name='TagMaster',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='users.tagmaster', verbose_name='Теги'),
        ),
    ]
