# Generated by Django 5.0.6 on 2024-06-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_tagpost_tagmaster_user_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=0, verbose_name='Статус мастера'),
        ),
    ]
