# Generated by Django 5.0.6 on 2024-06-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_is_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmaster',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, verbose_name='proverks'),
        ),
    ]
