# Generated by Django 5.0.6 on 2024-07-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_tagmaster_options_user_tags_mele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags_mele',
        ),
    ]
