# Generated by Django 5.0.6 on 2024-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_tags_mele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='О мастере'),
        ),
    ]
