# Generated by Django 5.0.6 on 2024-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_contactus_subject_alter_contactus_text_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
