# Generated by Django 5.0.6 on 2024-07-04 06:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('is_published', django.db.models.manager.Manager()),
            ],
        ),
    ]
