# Generated by Django 5.0.6 on 2024-07-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comment_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
