# Generated by Django 5.0.6 on 2024-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='text_mes',
            field=models.TextField(max_length=500, verbose_name='Текст'),
        ),
    ]
