# Generated by Django 5.0.6 on 2024-07-17 10:51

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_alter_contactus_text_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500, validators=[comments.models.RussianValidator], verbose_name='Комментарий'),
        ),
    ]
